version: '3'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    # name: 'mongodatabase1'
  docket-cat:
    image: docker-cat
    depends_on:
      - mongo
    ports:
      - '3000'
    links:
      - 'mongo:database'
    environment:
      ip: 'mongo'
    scale: 3
