version: '3'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    # filter:
    #   name: 'mongodatabase1'
    container_name: 'mongodatabase1'

    # volumes:
    #   - 'mongo:/data/db'
  docket-cat:
    deploy:
      replicas: 3
    image: docker-cat
    depends_on:
      - mongo
    ports:
      - '3000:3000'
    links:
      - 'mongo:database'
    environment:
      ip: 'mongo'
    # environment:
    #   MONGO_URI: 'mongodb://database:27017/test'
    # scale: 3
