version: '3'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  docket-cat:
    image: docker-cat
    # depends_on:
    #   - mongo
    ports:
      - '3000'
    links:
      - 'mongo:database'
    # environment:
    #   MONGO_URI: 'mongodb://database:27017/test'
    scale: 3
